/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2DPBO;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;

/**
 *
 * @author Kristiyant Ponty Y
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    static dbConnection db = new dbConnection();
    private boolean idol = true;
    
    public Main() {
        initComponents();
        setData();
    }
    
    public void setData(){
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        String sql = "SELECT * FROM tabelagensi";
        if(this.idol){
            sql = "SELECT * FROM tabelidol";
        }
        try{  
            ResultSet res = db.Query(sql);
            while(res.next()){
                if(this.idol == true){
                    PanelIdol card1 = new PanelIdol(res.getInt("id"), this); 
                    card1.setBorder(BorderFactory.createLineBorder(Color.black));
                    mainPanel.add(card1);
                }
                else{
                    PanelAgensi card2 = new PanelAgensi(res.getInt("id"), this); 
                    card2.setBorder(BorderFactory.createLineBorder(Color.black));
                    mainPanel.add(card2);
                }
            }            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnagensi = new javax.swing.JButton();
        btnidol = new javax.swing.JButton();
        addidol = new javax.swing.JButton();
        addagensi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA KPOP FANS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA KPOP FANS");

        btnagensi.setBackground(new java.awt.Color(255, 51, 0));
        btnagensi.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnagensi.setForeground(new java.awt.Color(255, 255, 255));
        btnagensi.setText("Agensi");
        btnagensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagensiActionPerformed(evt);
            }
        });

        btnidol.setBackground(new java.awt.Color(255, 51, 0));
        btnidol.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnidol.setForeground(new java.awt.Color(255, 255, 255));
        btnidol.setText("Idol");
        btnidol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidolActionPerformed(evt);
            }
        });

        addidol.setBackground(new java.awt.Color(255, 51, 0));
        addidol.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        addidol.setForeground(new java.awt.Color(255, 255, 255));
        addidol.setText("Add Idol");
        addidol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addidolActionPerformed(evt);
            }
        });

        addagensi.setBackground(new java.awt.Color(255, 51, 0));
        addagensi.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        addagensi.setForeground(new java.awt.Color(255, 255, 255));
        addagensi.setText("Add Agensi");
        addagensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addagensiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnagensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnidol)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addidol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addagensi, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagensi)
                    .addComponent(btnidol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(addidol)
                .addGap(18, 18, 18)
                .addComponent(addagensi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagensiActionPerformed
        // TODO add your handling code here:
        idol = false;
        setData();
    }//GEN-LAST:event_btnagensiActionPerformed

    private void btnidolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidolActionPerformed
        // TODO add your handling code here:
        idol = true;
        setData();
    }//GEN-LAST:event_btnidolActionPerformed

    private void addidolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addidolActionPerformed
        // TODO add your handling code here:
        FormIdol add = new FormIdol(this);
        add.setVisible(true);
        //add.setDefaultCloseOperation(FormIdol.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addidolActionPerformed

    private void addagensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addagensiActionPerformed
        // TODO add your handling code here:
        FormAgensi add = new FormAgensi(this);
        add.setVisible(true);
        //add.setDefaultCloseOperation(FormAgensi.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addagensiActionPerformed

    /**
     * @param args the comman d line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addagensi;
    private javax.swing.JButton addidol;
    private javax.swing.JButton btnagensi;
    private javax.swing.JButton btnidol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
