/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2DPBO;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Kristiyant Ponty Y
 */

public class PanelIdol extends javax.swing.JPanel {

    /**
     * Creates new form PanelIdol
     */
    
    static dbConnection db = new dbConnection();
    private int id;
    private tp2DPBO.Main main;
    private File foto;
    
    public PanelIdol(int id, tp2DPBO.Main main) {
        initComponents();
        this.id = id;
        this.main = main;
        setIdol();
    }
    
    public void setIdol(){
        try{
            String sql = "SELECT * FROM tabelidol WHERE id = '"+this.id+"'";
            ResultSet res = db.Query(sql);
            while(res.next()){
                labelGroup.setText(res.getString("nama"));
                labelAgensi.setText(res.getString("agensi"));
                labelDebut.setText(res.getString("tahun"));
                labelMember.setText(res.getString("member"));
                BufferedImage pic = null;
                this.foto = new File("src/foto/idol/" +res.getString("img"));
                pic = ImageIO.read(this.foto);
                Image dimg = pic.getScaledInstance(120, 150, Image.SCALE_SMOOTH);
                img.setIcon(new javax.swing.ImageIcon(dimg));
            }
        } catch(SQLException | IOException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelGroup = new javax.swing.JLabel();
        labelAgensi = new javax.swing.JLabel();
        labelDebut = new javax.swing.JLabel();
        labelMember = new javax.swing.JLabel();
        updateIdol = new javax.swing.JButton();
        deleteIdol = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Group");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agensi");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tahun Debut");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Member");

        labelGroup.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        labelGroup.setForeground(new java.awt.Color(255, 255, 255));
        labelGroup.setText("NamaIdol");

        labelAgensi.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        labelAgensi.setForeground(new java.awt.Color(255, 255, 255));
        labelAgensi.setText("NamaAgensi");

        labelDebut.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        labelDebut.setForeground(new java.awt.Color(255, 255, 255));
        labelDebut.setText("TahunDebut");

        labelMember.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        labelMember.setForeground(new java.awt.Color(255, 255, 255));
        labelMember.setText("JumlahMember");

        updateIdol.setBackground(new java.awt.Color(255, 51, 0));
        updateIdol.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        updateIdol.setForeground(new java.awt.Color(255, 255, 255));
        updateIdol.setText("Update");
        updateIdol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIdolActionPerformed(evt);
            }
        });

        deleteIdol.setBackground(new java.awt.Color(255, 51, 0));
        deleteIdol.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        deleteIdol.setForeground(new java.awt.Color(255, 255, 255));
        deleteIdol.setText("Delete");
        deleteIdol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIdolActionPerformed(evt);
            }
        });

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGroup)
                            .addComponent(labelAgensi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDebut)
                                    .addComponent(labelMember))))
                        .addContainerGap(52, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateIdol)
                .addGap(28, 28, 28)
                .addComponent(deleteIdol)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelGroup))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelAgensi))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateIdol)
                    .addComponent(deleteIdol))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteIdolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIdolActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin", "Hapus data", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            try{
                String tabel = "tabelidol";
                db.stmt.execute("DELETE FROM tabelidol WHERE id = '"+id+"'");
                if(foto != null){
                    foto.delete();
                }
                
                this.main.setData();
                System.out.println("Delete Success!");
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "EROR", JOptionPane.INFORMATION_MESSAGE);
            }    
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
            System.out.println("Batal Dihapus!");
        }
    }//GEN-LAST:event_deleteIdolActionPerformed

    private void updateIdolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIdolActionPerformed
        // TODO add your handling code here:
        FormIdol form = new FormIdol(this.id, this.main);
        form.setVisible(true);
    }//GEN-LAST:event_updateIdolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteIdol;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAgensi;
    private javax.swing.JLabel labelDebut;
    private javax.swing.JLabel labelGroup;
    private javax.swing.JLabel labelMember;
    private javax.swing.JButton updateIdol;
    // End of variables declaration//GEN-END:variables
}
